[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.1"
actix-ws = "0.2.5"
anyhow = "1.0.70"
derive_more = "0.99.17"
env_logger = "0.10.0"
futures = "0.3.28"
lazy_static = "1.4.0"
log = "0.4.17"
mediasoup = "0.11.4"
nanoid = "0.4.0"
rand = "0.8.5"
serde = "1.0.160"
serde_json = "1.0.95"
uuid = "1.3.1"
