[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# async rt
futures = "0.3.28"
actix-rt = "2.8.0"
# http
actix-web = "4.3.1"
# ws
actix-ws = "0.2.5"
anyhow = "1.0.70"
derive_more = "0.99.17"
# voice
mediasoup = "0.11.4"
# logging
env_logger = "0.10.0"
log = "0.4.17"
# config
lazy_static = "1.4.0"
# random
nanoid = "0.4.0"
rand = "0.8.5"
# json
serde = "1.0.160"
serde_json = "1.0.95"
time = "0.3.20"
uuid = "1.3.1"
# postgres db
sqlx = { version = "0.6.2", features = [ "runtime-actix-rustls", "postgres", "macros", "json", "chrono" ] }
# password hashing
rust-argon2 = "1.0.0"

