name: Publish Package
run-name: "Build & Publish ${{ github.ref_name }} to GitHub Packages (${{ github.sha }})"

on:
  push:
    branches:
      - "staging"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up database
        run: ./setupdb.sh
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up BuildKit context
        run: docker buildx create --use --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host'
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          network: host
  archive-openapi-spec:
    runs-on: ubuntu-latest
    needs: build-and-publish
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up database
        run: ./dev/setupdb.sh
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run server
        run: docker run -d --rm --network host ${{ env.IMAGE_NAME }}:latest
      - name: Download openapi.json
        run: curl -o openapi.json http://localhost:8080/openapi.json
      - name: Upload openapi.json
        uses: actions/upload-artifact@v3
        with:
          name: openapi.json
          path: openapi.json
