name: Publish Package
run-name: "Publish ${{ github.ref_name }} to GitHub Packages"

on:
  push:
    branches:
      - "staging"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-publish:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Execute build script
          run: ./build.sh ${{ env.IMAGE_NAME }}
        - name: Log in to registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Push image
          run: docker push ${{ env.IMAGE_NAME }}