name: Publish Package
run-name: "Build & Publish ${{ github.ref_name }} to GitHub Packages (${{ github.sha }})"

on:
  push:
    branches:
      - "staging"

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build-and-publish:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Set up database
          run: ./dev/setup_db.sh
        - name: Set up BuildKit context
          run: docker buildx create --use --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement network.host'
        - name: Log in to registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: "${{ env.IMAGE_NAME }}:latest"
            cache-from: type=gha
            cache-to: type=gha,mode=max
            allow: network.host
            network: host